jobs:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
      
language: python
python:
    - 3.6
    - 3.7
    - 3.8
    #- pypy3.6-7.1.1

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

cache: pip

install:
  - pip install -r requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - python setup.py install

script:
  - echo 1


notifications:
  email:
    recipients:
      - giuseppedilena92@gmail.com
    on_success: never
    on_failure: never
